DjangoServer/urls.py
from django.contrib import admin
from django.urls import path, include
from FaxServer import views, urls
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('fax-server/', include('FaxServer.urls')),
    path('', views.index)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FaxServer/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.list, name='list'),
    path('new/', views.new, name='new'),
    path('detail/<int:fid>/', views.detail, name='detail'),
    path('ajax/matters/<int:clientid>/', views.ajax_matters, name='ajax_matters'),
    path('download/<int:fid>/', views.api_fax_media, name='api_fax_media'),
    path('api/fax-status-callback/', views.api_fax_callback, name='api_fax_callback')
]

FaxServer/models.py
from django.db import models, transaction
from .g_twilio import *
import twilio.base.exceptions

# Create your models here.
class StringLengths:
    DescLength = 15
    FullTitleLength = 50
    PhoneLength = 10
    ClientIdLength = 5
    MatterNumLength = 5
    FaxIdLength = 8


class Client(models.Model):
    ShortName = models.CharField(max_length=StringLengths.DescLength)
    FullName = models.CharField(max_length=StringLengths.FullTitleLength)
    ClientId = models.CharField(max_length=StringLengths.ClientIdLength, primary_key=True)

    @property
    def PrettyName(self):
        return str(self.ClientId).zfill(StringLengths.ClientIdLength) + ": " + str(self.ShortName)

    def __str__(self):
        return self.PrettyName


class Matter(models.Model):
    ShortName = models.CharField(max_length=StringLengths.DescLength)
    FullName = models.CharField(max_length=StringLengths.FullTitleLength)
    MatterNumber = models.IntegerField()
    ParentClient = models.ForeignKey(Client, on_delete=models.CASCADE)

    @property
    def MatterName(self):
        return str(self.MatterNumber).zfill(StringLengths.ClientIdLength) + ": " + str(self.ShortName)

    @property
    def PrettyName(self):
        result = str(self.ParentClient.ClientId).zfill(StringLengths.ClientIdLength)
        result += "."
        result +=  str(self.MatterNumber).zfill(StringLengths.MatterNumLength)
        return result

    def __str__(self):
        return self.PrettyName

class Fax(models.Model):
    # project specific fields
    ParentMatter = models.ForeignKey(Matter, on_delete=models.CASCADE)
    DateCreated = models.DateField(auto_now_add=True)

    # essential fields for faxes
    DestNumber = models.CharField(max_length=StringLengths.PhoneLength)
    Pdf = models.FileField(upload_to='pdfs/', null=True)

    # fields for data from twilio 
    FaxStatus = models.CharField(max_length=10, default='ready')
    TwilioId = models.CharField(max_length=50, null=True)
    TwilioErrorMessage = models.TextField(null=True)

    class Meta:
        verbose_name_plural = "faxes"
        ordering = ['-pk']

    @property
    def FullId(self):
        return "FID" + str(self.id).zfill(StringLengths.FaxIdLength)

    def __str__(self):
        return self.FullId

    @classmethod
    def Create(cls, p_matter, p_dest_number, p_pdf):
        fax = cls(ParentMatter=p_matter, dest_number=p_dest_number, pdf=p_pdf)
        fax.save()
        return fax


    def Send(self):
        try:
            tid = TwilioSendText(self)
            print('new tid:' + str(tid))
            self.TwilioId = tid
        except twilio.base.exceptions.TwilioRestException as e:
            self.FaxStatus = "error"
            self.TwilioId = ""
            self.TwilioErrorMessage = e.msg
        self.save()

        return self.TwilioId

    def ParseStatus(self, p_status):
        with transaction.atomic():
            query = Fax.objects.select_for_update().get(pk=self.pk)
            print('updating status value')
            query.FaxStatus = p_status
            query.save()
        return self

    @property
    def IsSent(self):
        return self.FaxStatus == 'delivered'

FaxServer/forms.py
from django import forms
from .models import StringLengths
from django.core import validators

PhoneRegex = "^[0-9]{" + str(StringLengths.PhoneLength) + "}$"
ClientNumberRegex = "^[0-9]{1," + str(StringLengths.ClientIdLength) + "}$"
MatterNumberRegex = "^[0-9]{1," + str(StringLengths.MatterNumLength) + "}$"


# use consts for phone and number lengths?
class NewFaxForm(forms.Form):
    SendNumber = forms.RegexField(regex=PhoneRegex, label='Destination Number')
    ClientNumber = forms.RegexField(regex=ClientNumberRegex, label='Client Number')
    MatterNumber = forms.RegexField(regex=MatterNumberRegex, label='Matter Number')
    UploadPDF = forms.FileField(label='Upload PDF', validators=[validators.FileExtensionValidator(['pdf'])])

class FilterFaxList(forms.Form):
    ClientNumber = forms.RegexField(regex=ClientNumberRegex, label='Client Number')
    MatterNumber = forms.RegexField(regex=MatterNumberRegex, label='Matter Number', required=False)

FaxServer/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.core import serializers
from .models import Fax, Matter, Client
from .fax_api import *
from .forms import NewFaxForm, FilterFaxList
from django.views.decorators.csrf import csrf_exempt

# Create your views here.


def ajax_matters(request, clientid):
    matters = ListMatters(clientid)
    matter_list = serializers.serialize('json', matters)
    return HttpResponse(matter_list, content_type="text/json")


def index(request):
    return redirect('list')


def new(request):
    client_list = ListClients()
    if request.method == 'POST':
        print("attempting to create new fax")
        form = NewFaxForm(request.POST, request.FILES)

        if form.is_valid():
            print("form valid")
            matter_number = form.cleaned_data['MatterNumber']
            print(matter_number)
            matter = Matter.objects.get(pk=matter_number)
            newfax = Fax(ParentMatter=matter, DestNumber=form.cleaned_data['SendNumber'])
            if request.FILES:
                newfax.Pdf = request.FILES['UploadPDF']
            newfax.save()
            newfax.Send()
            return redirect('detail', fid=newfax.id)
        else:
            print("form was not valid")
    else:
        print("opening blank form")
        form = NewFaxForm()

    context = {'form': form, 'clients': client_list}
    return render(request, 'new.html', context)


def detail(request, fid):
    fax = {}

    if GetFax(fid):
        fax = Fax.objects.get(pk=fid)
        matter = Matter.objects.get(pk=fax.ParentMatter.pk)
        client = Client.objects.get(pk=matter.ParentClient.pk)
    else:
        # error
        return list(request)

    context = {'fax': fax, 'matter': matter, 'client': client}
    return render(request, 'detail.html', context)


@csrf_exempt
def list(request):
    p = request.GET
    faxes = Fax.objects.all()
    client_list = ListClients()

    if request.method == 'POST':
        form = FilterFaxList(request.POST)
        if form.is_valid():
            print('form valid')
            client_number = form.cleaned_data['ClientNumber']
            matter_number = form.cleaned_data['MatterNumber']
            if client_number and matter_number:
                if Matter.objects.filter(ParentClient=client_number, MatterNumber=matter_number):
                    matter = Matter.objects.get(ParentClient=client_number, MatterNumber=matter_number)
                    faxes = Fax.objects.filter(ParentMatter=matter)
                else:
                    faxes = []
                pass
            elif client_number and Client.objects.filter(pk=client_number):
                parent_client = Client.objects.get(pk=client_number)
                matters = parent_client.matter_set.all()
                faxes = []
                for m in matters:
                    for f in Fax.objects.filter(ParentMatter=m):
                        faxes.append(f)
                pass
            else:
                faxes = []
    else:
        form = FilterFaxList()

    context = {'faxes': faxes, 'clients': client_list, 'form': form}
    return render(request, 'list.html', context)


def api_fax_media(request, fid):
    f = Fax.objects.get(id=fid)

    return HttpResponseRedirect(f.Pdf.url)


@csrf_exempt
def api_fax_callback(request):
    print('a request')

    if request.method == 'POST':
        r = request.POST
        print('make that a post request')
        fid = request.POST.get('SmsSid')
        print('found:' + str(fid))
        fax_list = Fax.objects.filter(TwilioId=fid)
        for fax in fax_list:
            print('new status:' + request.POST.get('SmsStatus'))
            fax.ParseStatus(request.POST.get('SmsStatus'))

    return JsonResponse({})

FaxServer/templates/base.html
<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <title>Fax Server</title>
    <meta content="" name="description">
    <meta content="width=device-width, initial-scale=1" name="viewport">

    <script crossorigin="anonymous" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-3.4.1.min.js"><\/script>')</script>

    <link crossorigin="anonymous" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"
          integrity="sha256-9mbkOfVho3ZPXfM7W8sV2SndrGDuh7wuyLjtsWeTI1Q=" rel="stylesheet"/>
    <link crossorigin="anonymous"
          href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/container.min.css"
          integrity="sha256-7rJADGJ6l3YF6uxVoTB1b6xhQb93nEsuYsCBmXQX7Ds=" rel="stylesheet"/>
    <link crossorigin="anonymous"
          href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/image.min.css"
          integrity="sha256-fq7fY32a0sYPnyJyXc44WisZyImTDTltXD4yOWD4DII=" rel="stylesheet"/>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-165773085-2"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-165773085-2');
    </script>


    <style type="text/css">

        #compact-fields {
            margin: unset
        }

        body {
            background-color: #FFFFFF;
        }

        html {
            scroll-behavior: smooth;
        }

        pre {
            margin: 0em;
        }


        .main.container {
            margin-top: 1em;
        }

        .ui.footer.segment {
            margin: 1em 0em 0em;
            padding: 1em 0em;
        }
    </style>

</head>

<body>


<div class="ui main container">
    <div class="ui inverted huge purple menu">
        <div class="ui container">
            <a class="active header item" href="{% url 'index' %}">
                Fax Server
            </a>
            <a class="item" href="{% url 'list' %}">
                List Faxes
            </a>
            <a class="item" href="{% url 'new' %}">
                Create Fax
            </a>
        </div>
    </div>
        <div id="text-container">
            {% block content %}{% endblock %}
        </div>
    </div>
</div>

<div class="ui vertical footer segment">
    <div class="ui center aligned container">
        <div class="ui horizontal small divided link list">
            <a class="item" href="#">Geoffrey Cline</a>
        </div>
    </div>


    <!-- Add your site or application content here -->

    <script crossorigin="anonymous" integrity="sha256-t8GepnyPmw9t+foMh3mKNvcorqNHamSKtKRxxpUEgFI="
            src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha256-kt0Dfi+mrxAU+iYsfDrkROHrb55Hi0lVWC7MT46/xnU="
            src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/accordion.min.js"></script>
    <script>

        $('.ui.dropdown')
          .dropdown()
        ;

    </script>
    {% block javascript %}{% endblock %}

</body>

</html>

FaxServer/templates/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="ui segment">
  <h2>View Fax</h2>
</div>
<div id="error-message" class="ui icon negative hidden message">
  <i class="warning icon"></i>
  <div class="content">
    <div class="header">
      Error: Fax Not Sent
    </div>
    <p>Twilio was unable to send the fax. {{ fax.TwilioErrorMessage }}</p>
  </div>
</div>
<table class="ui celled compact table">
  <tbody>
    <tr>
      <td><span style="font-weight:bold">Reference</span></td>
      <td>{{ fax.ParentMatter }}</td>
    </tr>
    <tr>
      <td><span style="font-weight:bold">Client</span></td>
      <td>{{ client.PrettyName }}</td>
    </tr>
    <tr>
      <td><span style="font-weight:bold">Matter</span></td>
      <td>{{ matter.MatterName }}</td>
    </tr>
    <tr>
      <td><span style="font-weight:bold">Date Created</span></td>
      <td>{{ fax.DateCreated}}</td>
    </tr>
    <tr>
      <td><span style="font-weight:bold">Fax Status</span></td>
      <td>
        <div class="ui fax-status large label">{{ fax.FaxStatus }}</div>
      </td>
    </tr>
    <tr>
      <td><span style="font-weight:bold">Destination Number</span></td>
      <td>{{ fax.DestNumber}}</td>
    </tr>
    <tr>
      <td><span style="font-weight:bold">Download</span></td>
      <td>
        <button onclick="window.location.href = `{% url 'api_fax_media' fax.id %}`;"
          class="ui right labeled icon small compact blue button">
          <i class="file pdf icon"></i>
          PDF
        </button>
      </td>
    </tr>

  </tbody>
</table>
<div class="ui fluid steps">
  <div id="step-rx" class="step">
    <i class="cloud upload icon"></i>
    <div class="content">
      <div class="title">Received</div>
    </div>
  </div>
  <div id="step-tx" class="step">
    <i class="fax icon"></i>
    <div class="content">
      <div class="title">Sending</div>
    </div>
  </div>
  <div id="step-dl" class="step">
    <i class="flag checkered icon"></i>
    <div class="content">
      <div class="title">Delivered</div>
    </div>
  </div>

</div>
<div id="load-message" class="ui hidden icon message">
  <i class="notched circle loading icon"></i>
  <div class="content">
    <div class="header">
      Processing ... just a moment
    </div>
    <p>The fax is being uploaded to Twilio for sending.</p>
  </div>
</div>
<iframe src="{{ fax.Pdf.url }}" width="100%" height="500px">
</iframe>


{% endblock %}
{% block javascript %}
<script>
  var fax_sent = "{{ fax.FaxStatus }}"
  if (fax_sent === "delivered") {
    $('#step-rx').attr("class", "completed step")
    $('#step-tx').attr("class", "completed step")
    $('#step-dl').attr("class", "completed step")
  }
  else if (fax_sent === "error") {
    $('#error-message').removeClass('hidden')
    $('#step-rx').attr("class", "disabled step")
    $('#step-tx').attr("class", "disabled step")
    $('#step-dl').attr("class", "disabled step")
  }
  else {
    $('#step-rx').attr("class", "active step")
    $('#step-tx').attr("class", "disabled step")
    $('#step-dl').attr("class", "disabled step")
    $('#load-message').removeClass('hidden')
    setTimeout(function () {
      location.reload();
    }, 2500);
  }

  $(document).ready(function () {
    $('.fax-status').each(function () {
      var status = $(this).text()
      switch (status) {
        case 'delivered':
          $(this).addClass("green")
          break;
        case 'error':
          $(this).addClass("red")
          break;
        default:
          $(this).addClass("purple")
          break;
      }
    });
  });
</script>
{% endblock %}

FaxServer/templates/list.html
{% extends "base.html" %}
{% block content %}
<div class="ui top attached segment">
    <h2>View Sent Faxes</h2>
</div>
<div class="ui bottom attached segment">
    <div class="ui form">
        <form id="filter-form" action="/fax-server/list/" method="post">
            {% csrf_token %}
            <div id="compact-fields" class="fields">
                <div class="field">
                    {{ form.ClientNumber.label_tag }}
                    {{ form.ClientNumber}}
                </div>
                <div class="field">
                    {{ form.MatterNumber.label_tag }}
                    {{ form.MatterNumber}}
                </div>
                <div class="field">
                    <label>&nbsp;</label>
                    <button type="submit" value="Submit" class="ui primary button">Filter</button>
                </div>
                <div class="field">
                    <label>&nbsp;</label>
                    <button onclick="ResetForm()" class="ui button">Reset</button>
                </div>
            </div>
        </form>
    </div>

</div>
<div id="target">

</div>
<table class="ui single line fluid table">
    <thead>
        <tr>
            <th>FaxID</th>
            <th>Matter</th>
            <th>Date Created</th>
            <th>Status</th>
            <th>Destination</th>
            <th>Download</th>
        </tr>
    </thead>
    <tbody>
        {% for fax in faxes %}
        <tr>
            <td><a href="{% url 'detail' fax.id %}">{{ fax.FullId }}</a></td>
            <td>{{ fax.ParentMatter }}</td>
            <td>{{ fax.DateCreated }}</td>
            <td>
                <div class="ui fax-status label">{{ fax.FaxStatus }}</div>
            </td>
            <td>{{ fax.DestNumber }}</td>
            <td>
                <button onclick="window.location.href = `{% url 'api_fax_media' fax.id %}`;"
                    class="ui right labeled icon small compact blue button">
                    <i class="file pdf icon"></i>
                    PDF
                </button>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan=6>No Faxes Found</td>
        </tr>
        {% endfor %}


    </tbody>
</table>


{% endblock %}
{% block javascript %}
<script>
    function ResetForm(){
        $('input').val('')
        $('#filter-form').submit()
    }

    $(document).ready(function () {
        $('.fax-status').each(function () {
            var s = $(this).text()
            switch (s) {
                case 'delivered':
                    $(this).addClass("green")
                    break;
                case 'error':
                    $(this).addClass("red")
                    break;
                default:
                    $(this).addClass("purple")
                    break;
            }
        });

        $("#id_ClientNumber").change(function (e) {
            var clientid = $("#id_ClientNumber").val();

            $.ajax({
                type: 'GET',
                url: `/fax-server/ajax/matters/${clientid}/`,
                success: function (response) {
                    $("#id_MatterNumber input").val('')
                    $("#id_MatterNumber option").remove()
                    response.forEach(function (matter, index) {
                        var tag = `<option value='${matter.pk}'>${matter.fields.MatterNumber}: ${matter.fields.ShortName}</option>`
                        $("#id_MatterNumber").append(tag)
                    });
                }
            });
        });
    });


</script>
{% endblock %}

FaxServer/templates/new.html
{% extends "base.html" %}}
{% block content %}
<div class="ui top attached segment">
    <h2>Create Outgoing Fax</h2>
</div>
<div class="ui attached green segment">
    <div class="ui form">
        <form action="/fax-server/new/" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}

            <div class="fields">
                <div class="field">
                    {{form.ClientNumber.label_tag}}
                    <select name="ClientNumber" id="id_ClientNumber" class="ui search dropdown">
                        <option value="">Client</option>
                        {% for client in clients %}
                        <option value="{{ client.ClientId }}">{{ client.PrettyName }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="field">
                    {{form.MatterNumber.label_tag}}
                    <select name="MatterNumber" id="id_MatterNumber" class="ui search dropdown">
                        <option value="">Matter</option>
                    </select>
                </div>
                <div class="field">

                    {{form.SendNumber.label_tag}}
                    <div class="ui left labeled input">
                        <div class="ui dropdown label">
                            <div class="text">+1</div>
                        </div>
                        <input name="SendNumber" id="id_SendNumber" type="text" placeholder="Destination Number">
                    </div>
                    {{ form.SendNumber.errors }}
                </div>
            </div>
    </div>
    <div class="ui attached segment">
        {{ form.UploadPDF.errors }}
        <div class="fields">

            {{ form.UploadPDF }}
        </div>
        <div class="fields">

        </div>

    </div>

</div>
<div class="ui bottom attached segment">
    <button type="submit" value="Submit" class="ui primary fluid button">
        Submit
    </button>
</div>
</form>
{% endblock %}
{% block javascript %}
<script>
    $(document).ready(function () {
    });

    $("#id_ClientNumber").change(function (e) {
        var clientid = $("#id_ClientNumber").val();

        $.ajax({
            type: 'GET',
            url: `/fax-server/ajax/matters/${clientid}/`,
            success: function (response) {
                $("#id_MatterNumber input").val('')
                $("#id_MatterNumber option").remove()
                response.forEach(function (matter, index) {
                    console.log(matter)
                    var tag = `<option value='${matter.pk}'>${matter.fields.MatterNumber}: ${matter.fields.ShortName}</option>`
                    $("#id_MatterNumber").append(tag)
                });
            }
        });
    });
</script>
{% endblock %}